apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behovsakkumulator
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  startup:
    path: /isalive
    initialDelay: 10
    failureThreshold: 6
    periodSeconds: 5
    timeout: 1
  liveness:
    path: /isalive
    failureThreshold: 6
    periodSeconds: 10
  readiness:
    path: /isready
    failureThreshold: 3
    periodSeconds: 10
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 128Mi
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  kafka:
    pool: "{{ kafka.pool }}"
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-behovsakkumulator-v1
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
